### PR TITLE
Updated tests for src/vessel-charging/messages/DeclineMessageParams.t…

### PR DESCRIPTION
**Pull request by sark01**
Fixed Issue #68 

## Description

This file tests deserialize method of the class exported by DeclineMessageParams.ts. It ensures that deserializing a serialized class instance will result in the original class instance.

## How Has This Been Tested?

I have executed `npm run jest` to check whether all my code changes are passing the tests.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sark01** [comment]
@TalAter @mariolo1985, Could you please help me in this.
Thanks

**Comment by mariolo1985** [comment]
Hey @sark01 I think your test looks good. I believe it is stopped on a build file check. I will look into it as soon as I can.

**Comment by sark01** [comment]
@mariolo1985, Sure thing. If there are any corrections required in this PR, please let me know.

Also, I find the work you guys are doing very interesting and would like to contribute more to DAVFoundation. Could you please point out other issues that I can work on?

Thank you.

**Comment by TalAter** [comment]
We added a new pre-commit hook that builds all the files from `/src` and places them in `/dist` and commits them.

The working copy of the repo you had must have been from before we added it, and so your commit didn't include those files. Travis caught that and stopped it.

I merged it myself after building those files.

Before doing any other issues, make sure to clone the latest version of the repo and running `npm install` again.

Thank you for the help @sark01 👍

We should have more open issues soon

**Comment by sark01** [comment]
Apologies for not updating my repo to the latest version, it won't happen again.
I am learning so much by contributing in this repo, thank you @TalAter @mariolo1985

**Pull request merged**
