### PR TITLE
Setting up docker

### PR DESCRIPTION
**Pull request by debragail**
Setting up docker for use for dav-js

### CODE REVIEW

**Comment by mariolo1985** [comment]
I am not too familiar with Docker. I will have to do some reading up on it. What are the benefits of Docker for this project?

Should we be committing yarn error files?

**Comment by TalAter** [comment]
Hi @debragail 

I see you have added docker and used it to setup a new web server which counts hits on it.
Could you explain the reasoning behind this pull request, what you are trying to improve or accomplish?

Thanks 👍

**Comment by debragail** [comment]
I’d like to use docker in order to consistently test and deploy dav-js.  It will make setting up the environment consistent using the docker yaml and can be used specifically in the near future for integration and unit testing, so in conjunction with jest.  Also it allows for easy install for others in the OSS community to use it for installing and versioning.  In the long run it scales well and offers the perks of containerization like consistency and security.  I can post some best practice and how it could relate to this project.

**Comment by debragail** [comment]
https://blogs.gartner.com/richard-watson/ok-get-dockers-great/

**Comment by debragail** [comment]
I can remove the yarn error log from the commit

**Comment by mariolo1985** [comment]
thanks for the info @debragail :+1: I was running into a message regarding `docker-compose.yml` file when trying to run the command `docker-compose up`. I pulled `docker-compose.yml` from your _docker-services_ branch and it continued. Do you want to add the `docker-compose.yml` file to this PR? Could you remove `yarn-error.log`? Yarn was hanging for me on Windows. Did it happen to you? I had to use NPM to finish package installs.

Anyways, `docker-compose up` stopped with a `ERROR: Windows named pipe error: The system cannot find the file specified. (code: 2)` :sweat_smile: I'm at step 4 [here ](https://docs.docker.com/compose/gettingstarted/) if you have any advice to finish running this?

**Comment by TalAter** [comment]
I think there can be merit in running `missioncontrol` in a docker and then running integration tests of `dav-js` against it.

But it feels like a bit out of the scope of what we want to accomplish now, and as there might be extensive API changes to `dav-js` soon, it seems like our time might be better spent elsewhere.

My main concerns are with the extra complication, the extra code that needs to be maintained, implementing an additional technology - all of which is more technical debt that needs to be maintained (for something which might become deprecated when the SDK changes drastically).

**Pull request closed without merging**
