### PR TITLE
WIP - updated preinstall and postinstall scripts for cross OS compatibility

### PR DESCRIPTION
**Pull request by mariolo1985**
## Description

Currently, the preinstall and postinstall scripts execute with `rm` and `cp` commands that are not available on Windows OS.

This is causing `npm install` to fail on Windows.

This is tricky since the preinstall script runs before any modules are installed. I could not use modules like `rimraf` or `fs-extra`. I used Node to handle the removing and copying files. Node should be installed on machines that runs NPM so it should be reliable.

```javascript
  "scripts": {
    // other scripts
    "preinstall": "(rm .git/hooks/* && cp ./.githooks/* .git/hooks) || true",
    "postinstall": "rm -f node_modules/web3/index.d.ts node_modules/web3/types.d.ts",
    // other scripts
  }
```

**Note:** `rm` and `cp` command is used in a dependency [gulp-ts-spellcheck](https://github.com/srfrnk/gulp-ts-spellcheck/blob/master/package.json#L10) and this is causing `npm install` to fail in this repo.

## Motivation and Context

So our community of Windows contributors can continue helping out on this project.

## How Has This Been Tested?

Ran `npm install`

**Note:** `rm` and `cp` command is used in a dependency [gulp-ts-spellcheck](https://github.com/srfrnk/gulp-ts-spellcheck/blob/master/package.json#L10) and this is causing `npm install` to fail in this repo.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by TalAter** [comment]
I like this.
@srfrnk - Can you test and merge? Also, I know you're against `gulp-ts-spellcheck` working in Windows, but how about doing the same there?

**Comment by srfrnk** [comment]
I would like to perform a proper design process for tasks issues that change design patterns being used in our code.
Please hold this issue until we can do that.

**Comment by srfrnk** [comment]
See https://github.com/DAVFoundation/dav-js/commit/ca2ea379b49b81e02fa1b4ac2556b115925827a6
Should make this PR obsolete

**Comment by TalAter** [comment]
@mariolo1985 Can you verify if this works in Windows?

**Comment by srfrnk** [comment]
Hey @mariolo1985 Can you please try now?
I removed the postinstall entirely for now.

**Comment by mariolo1985** [comment]
Hi @srfrnk the error above remains when I ran `npm install`. I re-forked this repo to ensure master and my fork are even.

It seems to be erroring out on `gulp-ts-spellcheck`'s post install script `(cp ./.githooks/* .git/hooks) || true`

**Comment by srfrnk** [comment]
@mariolo1985 This was an issue with `gulp-ts-spellcheck`. Published a new version now. Should fix it. Can you please try again?

**Comment by mariolo1985** [comment]
It looks like that fix did it @srfrnk :man_dancing: I was able to run `npm install` without erroring out and `npm run jest` for a sanity check.

**Comment by TalAter** [comment]
That's great news 🎆 

@mariolo1985 could you let the person who also got this error on the other issue know?

**Pull request closed without merging**
