### PR TITLE
Add /src/tests folder

### PR DESCRIPTION
**Pull request by debragail**
Moved tests.ts files to tests folder to tidy up directory structure.  Edited the path in order for tests to work.  All tests confirmed and past in this PR.

Updated package.json and config.jest still in pull request.

### CODE REVIEW

**Comment by mariolo1985** [comment]
Hey @debragail you must have worn out that `.` key on your keyboard 😆 

Could you look into 2 things before I merge it? There is a conflict between this and master on the `package.json` file for `webpack-cli` versions. It may just need a pull from master. Also, I am receive a Gulp error. It seems there is a migration path on how tasks are defined from `gulp@3.9.1` to `gulp@4.x.x` (https://fettblog.eu/gulp-4-parallel-and-series/). Could you look into resolve that if you are planning to upgrade Gulp? Thanks!

**Comment by mariolo1985** [comment]
It looks like you are going to use `package.json` from master so I added it into this branch along with some chores to get Travis to pass. These are great structure changes. I have merged it to master.

**Comment by TalAter** [comment]
@debragail , @mariolo1985  Next time, let's have an open discussion in an open issue when you have an idea for a major change before implementing or merging it.

We have a team of 7 developers in house (not to mention the open source team) working on these code bases, and all of the projects have a certain code style and project structure. Changing the structure of one project is something we prefer to discuss first with me and @srfrnk as it affects everyone working on all the project.

**Comment by mariolo1985** [comment]
Yes, that makes sense :+1: will do in the future.

**Comment by debragail** [comment]
I agree @TalAter I will definitely have a discussion.  Was just trying to get PRs going through too hastily and completely agree they need to be discussed first.

**Pull request merged**
